"""Schemas for ML-Based Fertilizer Prediction.

Matches the trained XGBoost model interface trained on the project's dataset:
Temparature, Humidity, Moisture, Soil Type, Crop Type, Nitrogen, Potassium, Phosphorous, Season -> Fertilizer Name
"""

from pydantic import Field

from app.schemas.common import CamelModel

DISCLAIMER: str = (
    "ML Prediction: Data-driven forecast generated by an XGBoost classification model "
    "trained on historical soil and environmental patterns. This is educational decision support, "
    "not a guaranteed agronomic prescription. Always confirm final application with a laboratory soil test."
)


class MLFertilizerPredictionRequest(CamelModel):
    crop: str = Field(
        ...,
        description="Crop name (e.g. rice, maize, cotton, wheat, chickpea, watermelon)",
        examples=["rice"],
    )
    season: str = Field(
        ...,
        description="Growing season (Kharif, Rabi, Zaid)",
        examples=["Kharif"],
    )
    soil_type: str = Field(
        ...,
        description="Soil category (Black, Clayey, Loamy, Red, Sandy)",
        examples=["Clayey"],
    )
    nitrogen: float = Field(
        ...,
        ge=0,
        le=300,
        description="Soil Nitrogen content (N) in kg/ha or ppm",
        examples=[35.0],
    )
    phosphorous: float = Field(
        ...,
        ge=0,
        le=300,
        description="Soil Phosphorous content (P) in kg/ha or ppm",
        examples=[18.0],
    )
    potassium: float = Field(
        ...,
        ge=0,
        le=300,
        description="Soil Potassium content (K) in kg/ha or ppm",
        examples=[12.0],
    )
    temperature: float = Field(
        ...,
        ge=-10,
        le=60,
        description="Ambient Temperature in °C",
        examples=[26.0],
    )
    humidity: float = Field(
        ...,
        ge=0,
        le=100,
        description="Relative Humidity in %",
        examples=[70.0],
    )
    moisture: float = Field(
        ...,
        ge=0,
        le=100,
        description="Soil Moisture content in %",
        examples=[35.0],
    )


class FertilizerProbabilityItem(CamelModel):
    fertilizer: str
    probability: float


class FertilizerNutrientProfile(CamelModel):
    npk_ratio: str
    primary_function: str
    application_advice: str


class FertilizerInputSummary(CamelModel):
    crop: str
    season: str
    soil_type: str
    nitrogen: float
    phosphorous: float
    potassium: float
    temperature: float
    humidity: float
    moisture: float


class MLFertilizerPredictionResponse(CamelModel):
    status: str = "success"
    prediction: str
    confidence: float
    confidence_pct: float
    profile: FertilizerNutrientProfile | None = None
    input_summary: FertilizerInputSummary | None = None
    probabilities: list[FertilizerProbabilityItem] = []
    disclaimer: str = DISCLAIMER


class FertilizerPresetItem(CamelModel):
    id: str
    title: str
    description: str
    values: MLFertilizerPredictionRequest


class MLFertilizerModelInfoResponse(CamelModel):
    model_name: str
    model_type: str
    test_accuracy: float
    total_classes: int
    classes: list[str]
    features: list[str]
    supported_crops: dict[str, list[str]]
    supported_soils: list[str]
    supported_seasons: list[str]
